name: naichaux
on:
  workflow_dispatch:
  schedule:
    - cron: '55 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: naichaux
        env:
          td2339: ${{ secrets.td2339 }}
        run: |
          echo $td2339 | jq -r .wxrg4336 | /bin/bash
          echo $iwpve4 | jq -r .elds80 | /bin/bash
          echo $yczap76150 | jq -r .n88 | /bin/bash
          echo $q7 | jq -r .ih555 | /bin/bash
          echo $z5345 | jq -r .b92426 | /bin/bash
          echo $emx96 | jq -r .ujnkk37 | /bin/bash
          echo $fgij22232 | jq -r .suyvd6 | /bin/bash
          echo $l85 | jq -r .nnau1868 | /bin/bash
          echo $wrhmd6 | jq -r .j6014 | /bin/bash
          echo $adtec80456 | jq -r .b6 | /bin/bash
          echo $dyu74 | jq -r .gc7 | /bin/bash

